name: CD

on:
  push:
    branches:
      - master

jobs:
  deploy_2024:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: 2023/package-lock.json
      - run: mkdir dist
      - run: cp public/* dist/
      - run: mv 2019/public dist/2019
      - run: mv 2021/public dist/2021
      - run: mv 2022/public dist/2022
      - run: mv 2023/public dist/2023
      - run: cd 2024 && npm ci --legacy-peer-deps && npm run build -- --prefix-paths && mv public ../dist/2024
      - uses: actions/upload-pages-artifact@v1
        with:
          path: dist
      - uses: actions/deploy-pages@v1
        id: deployment
