name: screenshots

on:
  pull_request:
    branches: [main]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: 2026/.nvmrc
          cache: npm
          cache-dependency-path: 2026/package-lock.json
      - run: cd 2026 && npm ci
      - run: cd 2026 && npm run dev &
        env:
          PORT: 3001
      - run: cd 2026 && npx playwright install --with-deps
      - run: cd 2026 && npx playwright test
      - run: cd 2026 && npm run fetch-og-images
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: ${{ !cancelled() }}
        with:
          name: screenshots
          path: 2026/screenshots/**/*
          retention-days: 7
      - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const url = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `📦 Screenshots: [Download](${url})`
            });
